version: '3.3'

services:
  spring-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:9090"
    depends_on:
      - backend

volumes:
  db_data: {}

networks:
  backend:
